<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'TsvNews\Module'                        => __DIR__ . '/Module.php',
    'TsvNews\Controller\TsvNewsController' => __DIR__ . '/src/TsvNews/Controller/TsvNewsController.php',
    'TsvNewsTest\Framework\TestCase'        => __DIR__ . '/tests/TsvNews/Framework/TestCase.php',
    'TsvNewsTest\SampleTest'                => __DIR__ . '/tests/TsvNews/SampleTest.php',
);
