<script src="//cdn.ckeditor.com/4.4.2/full/ckeditor.js"></script>

<link rel="stylesheet" href="//code.jquery.com/ui/1.10.4/themes/smoothness/jquery-ui.css">
<script src="//code.jquery.com/ui/1.10.4/jquery-ui.js"></script>
<script src="https://jquery-ui.googlecode.com/svn-history/r3004/trunk/ui/i18n/ui.datepicker-ru.js"></script>
<script>
  $(function() {
    $( "#start_date" ).datepicker( $.datepicker.regional[ "ru" ] );
  });
  $(function() {
    $( "#end_date" ).datepicker( $.datepicker.regional[ "ru" ] );
  });
  $(function() {
    $( "#news_date" ).datepicker( $.datepicker.regional[ "ru" ] );
  });
</script>
<form method="post" name="edit-news" enctype="multipart/form-data" id="edit-news">
	<div class="row">
	  <div class="col-md-12">
			<h1>Редактировать новость</h1>
	  </div>
	</div>
	<br>
	<div class="row">
	  <div class="col-md-12">
			<input type="text" class="form-control" placeholder="Заголовок новости" value="<?php echo $this->title;?>" name="title" style="width:98%;" required>
	  </div>
	</div>
	<div class="row">
	  <div class="col-md-12">

	  		<br>
			<textarea rows="2" cols="300" placeholder="Краткий текст новости" class="form-control" name="short_content" style="width:98%;" required><?php echo $this->short_content;?></textarea>
	  </div>
	</div>
	<div class="row">
	  <div class="col-md-12">
			<br>
				  		<strong>Полный текст новости поддерживается html оформление.</strong>
			<br>
			<textarea name="content"><?php echo $this->content;?></textarea>
	  </div>
	</div>

	<br>
	<div class="row">
	  <div class="col-md-3">
			<strong>Тематическое изображение</strong>
	  </div>
	  <div class="col-md-9">
	  		<?php if($this->image) {?><img width="28" src="/img/news/<?php echo $this->image;?>" style="float:left;margin: 0px 10px 10px 0px;"><?php }?>
			<input type="file" class="input" id="file" name="image">
	  </div>
	</div>
	<br>
	
	<div class="row">
	  <div class="col-md-3">
			<strong>Дата начала отображения новости</strong>
	  </div>
	  <div class="col-md-9">
			<input type="text" class="input" id="start_date" value="<?php echo $this->start_date->format('d.m.Y');?>" name="start_date" required>
	  </div>
	</div>

	<br>
	<div class="row">
	  <div class="col-md-3">
			<strong>Дата окончания отображения новости</strong>
	  </div>
	  <div class="col-md-9">
			<input type="text" class="input" id="end_date" value="<?php echo $this->end_date->format('d.m.Y');?>" name="end_date" required>
	  </div>
	</div>
		
	<br>
	<div class="row">
	  <div class="col-md-3">
			<strong>Отображаемая дата новости</strong>
	  </div>
	  <div class="col-md-9">
			<input type="text" class="input" id="news_date" value="<?php echo $this->news_date->format('d.m.Y');?>" name="news_date" required>
			<input type="text" size="8" class="input" id="news_time" value="<?php echo $this->news_date->format('H:i:s');?>" name="news_time" required>
	  </div>
	</div>
		<br>
	<div class="row">
	  <div class="col-md-12">
			<button type="submit" class="btn btn-success">Сохранить</button>
			<button type="button" onclick="if(confirm('Хотите отменить сохранение?')) window.location.href='<?php echo $this->url('zfcadmin/tsv-news') ?>';" class="btn btn-warning">Отмена</button>
	  </div>
	</div>
</form>
<script>
CKEDITOR.replace( 'content', {allowedContent : true
});
</script>