<?php 
Zend\Paginator\Paginator::setDefaultScrollingStyle('Sliding');
Zend\View\Helper\PaginationControl::setDefaultViewPartial('partials/tsv_searchpagination.phtml');
?>

<div class="row">
  <div class="span4">
		<a class="btn btn-success" href="<?php echo $this->url('zfcadmin/tsv-news/default',array("action"=>"add"));?>">Добавить новость</a>
  </div>
</div>
<br>
<div class="row">
  <div class="span12">
  
		<?php 
		foreach ($paginator as $row)
		{?>
		
		 <hr>
          	<div class="btn-group" style="float:right;">
			  <div class="btn-group">
			    <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
			      Управление
			      <span class="caret"></span>
			    </button>
			    <ul class="dropdown-menu">
			      <li><a href="<?php echo $this->url('zfcadmin/tsv-news/default', array('action'=>'edit','id'=>$row->__get('id'))) ?>">Редактировать</a></li>
			      <li><a onclick="if(!confirm('Вы действительно хотите удлаить нанную новость?')) return false;" href="<?php echo $this->url('zfcadmin/tsv-news/default', array('action'=>'delete','id'=>$row->__get('id'))) ?>">Удалить</a></li>
			    </ul>
			  </div>
			</div>
		 <h1><?php echo $row->__get('title');?></h1>
		 
		 <?php if($row->__get('disabled_news')) echo "<a class='btn btn-small btn-success' style='float:right;' href='".$this->url('zfcadmin/tsv-news/default', array('action'=>'enableNews','id'=>$row->__get('id'),'page'=>$this->paginator->getCurrentPageNumber()))."'>Включить</a>"?>
		 <?php if(!$row->__get('disabled_news')) echo "<a class='btn btn-small btn-warning' style='float:right;' href='".$this->url('zfcadmin/tsv-news/default', array('action'=>'disableNews','id'=>$row->__get('id'),'page'=>$this->paginator->getCurrentPageNumber()))."'>Отключить</a>"?>
		 
          <p><i style="color:gray;"><?php echo $row->__get('short_content');?></i></p>
          <?php if($row->__get('image')) {?><img width="128" alt="Апартаменты в стиле лофт" src="/img/news/<?php echo $row->__get('image');?>" style="float:left;margin: 0px 10px 10px 0px;"><?php }?>
          <p><?php echo $row->__get('content');?></p>
        <div style="clear:both;"></div>
        <font size="-2">
        Дата начала отображения: <?php echo $row->__get('start_date')->format('d.m.Y');?><br>        
        Дата окончания отображения: <?php echo $row->__get('end_date')->format('d.m.Y');?><br>        
        Отображаемая дата новости: <?php echo $row->__get('news_date')->format('d.m.Y H:i:s');?><br>
        <?php if($row->__get('meta_title')){?>        
        Meta-title: <?php echo $row->__get('meta_title');?><br>
        <?php }?>
        <?php if($row->__get('meta_title')){?>        
        Meta-description: <?php echo $row->__get('meta_description');?><br>
        <?php }?>
		</font>
		
			
			<?php 
		}
		?>

		
<?php 
	echo $this->paginationcontrol($paginator); 
?>
</div>
</div>	