<?php 
Zend\Paginator\Paginator::setDefaultScrollingStyle('Sliding');
Zend\View\Helper\PaginationControl::setDefaultViewPartial('partials/tsv_searchpagination.phtml');
?>

<div class="row">
  <div class="span4">
		<a class="btn btn-success" href="<?php echo $this->url('zfcadmin/tsv-news/default',array("action"=>"add"));?>">Добавить новость</a>
  </div>
</div>
<br>
<div class="row">
  <div class="span12">
  
		<?php 
		
		foreach ($paginator as $row)
		{?>
		
		 <hr>
		  <h1><?php echo $row->__get('title');?></h1>
          <?php echo $row->__get('content');?>
          
          	<div class="btn-group" style="float:right;">
			  <div class="btn-group">
			    <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
			      Управление
			      <span class="caret"></span>
			    </button>
			    <ul class="dropdown-menu">
			      <li><a href="<?php echo $this->url('zfcadmin/tsv-directory/editor', array('action'=>'editSection','id'=>$row->__get('id'))) ?>">Редактировать</a></li>
			      <li><a onclick="if(!confirm('Вы действительно хотите удлаить данный раздел данных')) return false;" href="<?php echo $this->url('zfcadmin/tsv-directory/remover', array('action'=>'removeSection','id'=>$row->__get('id'))) ?>">Удалить</a></li>
			    </ul>
			  </div>
			</div>
			
			<?php 
		}
		?>

		
<?php 
	echo $this->paginationcontrol($paginator); 
?>
</div>
</div>	